version: "3.8"
services:
  frontend-dev:
    image: eduardomelodeoliveira/gyro-application-prod:frontend-v4
    container_name: gyro-frontend-dev-container
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true