version: "3.8"
services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: gyro-frontend-dev-container
    volumes:
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true