name: Frontend CI/CD

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: eduardomelodeoliveira/gyro-application-prod:frontend-v15

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_IMAGE ./gyro-front-end
          docker push $DOCKER_IMAGE

      - name: SSH into Public Instance and update Frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PUBLIC_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
              cd ~/infra
              sudo docker-compose pull frontend-dev
              sudo docker-compose up -d --no-deps --build frontend-dev

